spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true # @PageableDefault Pageable 에 대해서 작동
        default-page-size: 5
  datasource:
    url: jdbc:h2:mem:hodolog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true # data.sql 실행용
  sql:
#    init:
#      mode: always # data.sql 실행용 -> 가입기능 만들면서 삭제

hodolman:
  jwt-kwy: "rTPmA9Sgk+Q1Xwu]bG7E6xFFUhQpdi+a151yPnRTK/Q="