# ### 로그인
#POST localhost:8080/auth/login
#Content-Type: application/json
#
#{
#  "email": "hodolman88@gmail.com",
#  "password" : "1234"
#}

### 회원가입
POST localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "호돌맨",
  "email": "hodolman88@gmail.com",
  "password": "1234"
}


### 로그인 - 시큐리티 폼
POST localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=hodolman&password=1234&remember=1

### 메인페이지
GET http://localhost:8080/

### 인증 페이지 요청

GET localhost:8080/foo
Content-Type: application/json
Cookie: SESSION=9a60d19a-486e-45c4-ba13-d0b2acb64ef2